// JobSummaryDrawer.tsx
//
// The AI Summary feature panel: fetch orchestration + the three sections
// (Missions, Key Skills, Accommodations), rendered inside the generic
// SummaryDrawer shell.
//
// Strings live in a local per-language record, matching the only translation
// convention this codebase has today (Login.tsx:128 does the same). There is
// no i18n library — reported, not invented here.
//
// Skill matching reuses SkillBadges + jobSkillMatchesCandidate unchanged. No
// matching logic is written in this file.

import { useCallback, useEffect, useRef, useState } from "react";
import { AlertCircle, Info } from "lucide-react";
import SummaryDrawer from "./SummaryDrawer";
import SkillBadges from "./SkillBadges";
import { Language } from "../types";
import { useLanguageStore } from "../store/languageStore";
import {
  fetchJobSummary,
  getCachedSummary,
  isAbortError,
  SummaryError,
  type JobSummaryContent,
  type SummaryErrorCode,
} from "../services/aiSummaryService";

type Strings = {
  title: string;
  close: string;
  missions: string;
  keySkills: string;
  accommodations: string;
  emptyMissions: string;
  emptySkills: string;
  emptyAccommodations: string;
  disclosure: string;
  loading: string;
  ready: string;
  errors: Record<SummaryErrorCode, string>;
};

const STRINGS: Record<Language, Strings> = {
  [Language.EN]: {
    title: "AI summary",
    close: "Close the AI summary",
    missions: "Missions",
    keySkills: "Key skills",
    accommodations: "Accommodations",
    emptyMissions: "No missions stated in this offer.",
    emptySkills: "No skills stated in this offer.",
    emptyAccommodations: "No accommodations stated in this offer.",
    disclosure:
      "Summary generated by AI. The full offer text remains the authoritative version.",
    loading: "Generating the summary…",
    ready: "Summary ready.",
    errors: {
      INVALID_JOB_ID: "This job reference is not valid.",
      INVALID_LANG: "This language is not available for summaries.",
      JOB_NOT_FOUND: "This job offer no longer exists.",
      JOB_NOT_AVAILABLE: "This job offer is closed, so it cannot be summarized.",
      RATE_LIMITED: "Too many summaries requested. Please try again later.",
      SUMMARY_UNAVAILABLE: "The summary is temporarily unavailable. Please try again later.",
      NETWORK: "The summary could not be loaded. Check your connection and try again.",
    },
  },
  [Language.FR]: {
    title: "Résumé IA",
    close: "Fermer le résumé IA",
    missions: "Missions",
    keySkills: "Compétences clés",
    accommodations: "Aménagements",
    emptyMissions: "Aucune mission précisée dans cette offre.",
    emptySkills: "Aucune compétence précisée dans cette offre.",
    emptyAccommodations: "Aucun aménagement précisé dans cette offre.",
    disclosure:
      "Résumé généré par IA. Le texte complet de l'offre reste la version qui fait foi.",
    loading: "Génération du résumé…",
    ready: "Résumé disponible.",
    errors: {
      INVALID_JOB_ID: "Cette référence d'offre n'est pas valide.",
      INVALID_LANG: "Cette langue n'est pas disponible pour les résumés.",
      JOB_NOT_FOUND: "Cette offre n'existe plus.",
      JOB_NOT_AVAILABLE: "Cette offre est fermée, elle ne peut pas être résumée.",
      RATE_LIMITED: "Trop de résumés demandés. Veuillez réessayer plus tard.",
      SUMMARY_UNAVAILABLE: "Le résumé est momentanément indisponible. Réessayez plus tard.",
      NETWORK: "Le résumé n'a pas pu être chargé. Vérifiez votre connexion et réessayez.",
    },
  },
  [Language.AR]: {
    title: "ملخص الذكاء الاصطناعي",
    close: "إغلاق ملخص الذكاء الاصطناعي",
    missions: "المهام",
    keySkills: "المهارات الأساسية",
    accommodations: "الترتيبات التيسيرية",
    emptyMissions: "لا توجد مهام مذكورة في هذا العرض.",
    emptySkills: "لا توجد مهارات مذكورة في هذا العرض.",
    emptyAccommodations: "لا توجد ترتيبات تيسيرية مذكورة في هذا العرض.",
    disclosure:
      "ملخص تم إنشاؤه بالذكاء الاصطناعي. يبقى النص الكامل للعرض هو المرجع المعتمد.",
    loading: "جارٍ إنشاء الملخص…",
    ready: "الملخص جاهز.",
    errors: {
      INVALID_JOB_ID: "مرجع هذا العرض غير صالح.",
      INVALID_LANG: "هذه اللغة غير متاحة للملخصات.",
      JOB_NOT_FOUND: "لم يعد هذا العرض موجودًا.",
      JOB_NOT_AVAILABLE: "هذا العرض مغلق، لذلك لا يمكن تلخيصه.",
      RATE_LIMITED: "تم طلب عدد كبير من الملخصات. يرجى المحاولة لاحقًا.",
      SUMMARY_UNAVAILABLE: "الملخص غير متاح مؤقتًا. يرجى المحاولة لاحقًا.",
      NETWORK: "تعذّر تحميل الملخص. تحقق من اتصالك وحاول مرة أخرى.",
    },
  },
};

export type JobSummaryDrawerProps = {
  open: boolean;
  jobId: string;
  onClose: () => void;
  /** Candidate profile skills; omitted when no profile exists (guest view). */
  candidateSkills?: string[];
};

function SectionHeading({ children }: { children: string }) {
  return (
    <h3 className="text-sm font-bold uppercase tracking-wide text-text-secondary">
      {children}
    </h3>
  );
}

function EmptyState({ children }: { children: string }) {
  return <p className="text-sm text-text-secondary">{children}</p>;
}

function SummarySkeleton() {
  return (
    <div className="space-y-6">
      {[0, 1, 2].map((section) => (
        <div key={section} className="space-y-2">
          <div className="h-3 w-28 rounded bg-gray-200" />
          <div className="h-3 w-full rounded bg-gray-100" />
          <div className="h-3 w-4/5 rounded bg-gray-100" />
        </div>
      ))}
    </div>
  );
}

export default function JobSummaryDrawer({
  open,
  jobId,
  onClose,
  candidateSkills,
}: JobSummaryDrawerProps) {
  const lang = useLanguageStore((state) => state.lang);
  const t = STRINGS[lang];
  const isRtl = lang === Language.AR;

  const [content, setContent] = useState<JobSummaryContent | null>(null);
  const [errorCode, setErrorCode] = useState<SummaryErrorCode | null>(null);
  const [loading, setLoading] = useState(false);

  // StrictMode mounts effects twice in dev. This ref remembers which
  // (jobId, lang) pair has already been requested by THIS component, so the
  // second invocation is a no-op rather than a second HTTP call.
  const requestedKeyRef = useRef<string | null>(null);

  useEffect(() => {
    if (!open) {
      requestedKeyRef.current = null;
      return undefined;
    }

    const key = `${jobId}::${lang}`;
    if (requestedKeyRef.current === key) return undefined;
    requestedKeyRef.current = key;

    const cached = getCachedSummary(jobId, lang);
    if (cached) {
      setContent(cached.summary);
      setErrorCode(null);
      setLoading(false);
      return undefined;
    }

    const controller = new AbortController();
    setLoading(true);
    setErrorCode(null);
    setContent(null);

    fetchJobSummary(jobId, lang, controller.signal)
      .then((response) => {
        if (controller.signal.aborted) return;
        setContent(response.summary);
        setLoading(false);
      })
      .catch((error: unknown) => {
        if (isAbortError(error) || controller.signal.aborted) return;
        setErrorCode(error instanceof SummaryError ? error.code : "NETWORK");
        setLoading(false);
      });

    return () => controller.abort();
  }, [open, jobId, lang]);

  const handleClose = useCallback(() => {
    onClose();
  }, [onClose]);

  const liveMessage = loading ? "" : errorCode ? t.errors[errorCode] : content ? t.ready : "";

  return (
    <SummaryDrawer
      open={open}
      title={t.title}
      closeLabel={t.close}
      onClose={handleClose}
      isRtl={isRtl}
      busy={loading}
    >
      <div role="status" aria-live="polite" className="sr-only">
        {liveMessage}
      </div>

      <p className="mb-4 flex items-start gap-2 rounded-lg bg-indigo-50/60 px-3 py-2 text-xs leading-relaxed text-indigo-900">
        <Info className="mt-0.5 h-4 w-4 shrink-0 text-indigo-600" aria-hidden="true" />
        <span>{t.disclosure}</span>
      </p>

      {loading ? <SummarySkeleton /> : null}

      {!loading && errorCode ? (
        <p className="flex items-start gap-2 text-sm text-red-700">
          <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
          <span>{t.errors[errorCode]}</span>
        </p>
      ) : null}

      {!loading && !errorCode && content ? (
        <div className="space-y-6">
          <section className="space-y-2">
            <SectionHeading>{t.missions}</SectionHeading>
            {content.main_missions.length > 0 ? (
              <ul className="list-disc space-y-1 pl-5 text-sm text-text-primary">
                {content.main_missions.map((mission, index) => (
                  <li key={`${mission}-${index}`}>{mission}</li>
                ))}
              </ul>
            ) : (
              <EmptyState>{t.emptyMissions}</EmptyState>
            )}
          </section>

          <section className="space-y-2">
            <SectionHeading>{t.keySkills}</SectionHeading>
            {content.key_skills.length > 0 ? (
              <SkillBadges
                skills={content.key_skills}
                candidateSkills={candidateSkills}
              />
            ) : (
              <EmptyState>{t.emptySkills}</EmptyState>
            )}
          </section>

          <section className="space-y-2">
            <SectionHeading>{t.accommodations}</SectionHeading>
            {content.accommodations.length > 0 ? (
              <ul className="list-disc space-y-1 pl-5 text-sm text-text-primary">
                {content.accommodations.map((item, index) => (
                  <li key={`${item}-${index}`}>{item}</li>
                ))}
              </ul>
            ) : (
              <EmptyState>{t.emptyAccommodations}</EmptyState>
            )}
          </section>
        </div>
      ) : null}
    </SummaryDrawer>
  );
}
